version: '3'

application:
  env: debug  # 合法选项 "" (默认为空 = debug ) "debug" "release" "test"
  host: 0.0.0.0
  port: 8088

mysql:
  host: 192.168.174.148
  port: 3306
  user: root
  pwd: root
  db: casbin3
  prefix:

log:
  path:
  level: trace # 合法选项 "panic" "fatal" "error" "warn" "warning" "info" "debug" "trace"

casbin:
  path: